modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="Custom License"

[[mods]] #mandatory
modId="nika" #mandatory
version="1.0" #mandatory
displayName="The Devil fruits" #mandatory
authors="AugmentedWill" #optional
description="The Devil Fruits & Haki mod lets you eat one of several mythical fruits—like Dragon-Dragon, Quake-Quake, Dark-Dark and more—to gain a suite of powerful signature moves you unlock and master over time. After consuming your fruit, press R to cycle through fruit abilities, Z to activate the selected move, X for a quick-use, O to view your ultimate unlock conditions, and right-shift to awaken your ultimate form once you’ve met its mastery requirements. You can also unlock three forms of Haki by completing special Haki Book challenges—Armament (deal 10 000 fist damage), Observation (take 10 000 damage and then survive 15 m without being hit) and Conqueror’s (unique PvP kill challenge)—then cycle Haki with the arrow keys, select moves with H, and use Haki abilities with G; Armament boosts your damage and bypasses Observation defenses, Observation grants dodge and conditional immunity, and Conqueror’s emits a damaging aura that repels unprotected foes."

# [[mixins]]
# config="nika.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nika]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.nika]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
